### PR TITLE
Simplify the `bel_proper_list_p` function

### PR DESCRIPTION
**Pull request by masak**
We can eliminate one conditional by re-ordering the test and
stepping the iterator inside the loop.

### CODE REVIEW

**Comment by luksamuk** [comment]
Seems like I changed this function before you proposed this change, however I'll favor yours instead of mine. Thank you so much.

**Comment by luksamuk** [comment]
I had to make some extra work when integrating this since there were new changes, so it is merged under 7ade998. Github did not see if for some reason. Thanks for the contribution.

**Comment by masak** [comment]
@luksamuk Hi, sorry, I realized I have a question. 😊 

For future PRs, would you prefer me to make the same change in both `believe-literate.org` and `believe.c`? Looking at some prior history, I'm led to believe that's how I should have done my code changes.

I don't have an environment set up yet where I can do tangling. I'll work on that as well.

**Comment by masak** [comment]
> I'm led to believe

Oh dear. No pun intended. 😮

**Comment by luksamuk** [comment]
> For future PRs, would you prefer me to make the same change in both `believe-literate.org` and `believe.c`?

That will not be necessary; just change `believe-literate.org` and we're all set. `believe.c` is not supposed to be changed by hand anyway.

Perharps sometime in the future I might consider creating a CI solution for tangling and testing, but until I have the parser up and running, I won't be able to do that...

**Pull request closed without merging**
